namespace:
  name: sandbox
 
service:
  port: 4111
  type: ClusterIP
  protocol: TCP
  targetPort: 3111

image:
  repository: benhe89/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  
  limits:
    cpu: 500m
    memory: 128Mi

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz


